apiVersion: v1
kind: Service
metadata:
  labels:
    run: trade-derby-web
  name: trade-derby-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: trade-derby-web
  type: LoadBalancer
status:
  loadBalancer: {}