apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-derby
  labels:
    app: trade-derby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-derby
  template:
    metadata:
      labels:
        app: trade-derby
    spec:
      containers:
      - name: trade-derby-container
        image: gcr.io/gke-trade-derby/trade-derby:latest
        command: ["/hello",
                  "--number=$(ENV_NUMBER)"]
        ports:
        - containerPort: 8080
        env:
        - name: ENV_NUMBER
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: env_number

