apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-derby
  labels:
    app: trade-derby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-derby
  template:
    metadata:
      labels:
        app: trade-derby
    spec:
      containers:
      - name: trade-derby-container
        image: gcr.io/gke-trade-derby/trade-derby:latest
        imagePullPolicy: Always
        command: ["/trade-derby",
                  "--number=$(ENV_NUMBER)"]
        ports:
        - containerPort: 8080
        env:
        - name: ENV_NUMBER
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: env_number
        - name: APPUSER
          valueFrom:
            secretKeyRef:
              name: kube-user
              key: username
        - name: APPPASS
          valueFrom:
            secretKeyRef:
              name: kube-pass
              key: password
        - name: TRADEDERBY_SHEETID
          valueFrom:
            secretKeyRef:
              name: kube-tradederby-sheetid
              key: tradederby_sheetid
        volumeMounts:
          - name: trade-derby-serviceaccount-volume
            mountPath: /etc/tradederby
            readOnly: true
      volumes:
      - name: trade-derby-serviceaccount-volume
        secret:
          secretName: kube-trade-derby-serviceaccount