kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: trade-derby

resources:
- deployment.yaml
- service.yaml
- configMap.yaml

generatorOptions:
  disableNameSuffixhash: true
secretGenerator:
- name: kube-user
  files:
  - username=username.txt
- name: kube-pass
  files:
  - password=password.txt

