kind: Service
apiVersion: v1
metadata:
  labels:
    app: trade-derby
  name: trade-derby-service
spec:
  selector:
    app: trade-derby
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
